on: ["push", "pull_request"]

name: Test Coveralls
env:
  github-token: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: make test-unit
      run: |
        make test-unit

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        file: tests_super/unitario/cobertura.xml
